简化了MapPolygon.maskout，修改了drawing中裁剪的制作。
cnmetlab/cnmaps pull request #77
Opened 2022-08-18 13:57 UTC by ZhaJiMan

对于 [Issue#74](https://github.com/cnmetlab/cnmaps/issues/74) 的问题，用 line_profiler 查看发现大部分时间都花在了 `_make_clip_path` 中新建 `Path` 对象的语句上

```Python
_clip = mpath.Path(vertices, codes)
```

参考 [气象绘图加强版（十二）——白化杂谈](https://mp.weixin.qq.com/s/CGjvTAIArmZEp9N0B0jrew) 中对 `cartopy.mpl.patch.geos_to_path` 函数的使用，重写了 `_make_clip_path` 函数，输入一个 `map_polygon` 只会返回一个 `Path`，可以直接用来裁剪 `Collection` 对象。以 [Issue#74](https://github.com/cnmetlab/cnmaps/issues/74) 的代码为例，修改前我的本地运行时间是 33 秒，修改后变为 1.5 秒。修改后 `drawing` 中各种 `clip_` 函数的效果按文档的代码进行了测试，未发现异常。

`MapPolygon.maskout` 之前用的是递归的算法，我在看 [regionmask 的文档](https://regionmask.readthedocs.io/en/stable/notebooks/method.html) 时发现 regionmask 用了 `shapely.vectorized.contains` 函数，一行就能生成掩膜

```Python
from shapely.vectorized import contains
contains(map_polygon, lons, lats)
```

就可以把那一大段代码替换成简单的一行。测试速度如下

![timing_new](https://user-images.githubusercontent.com/54382968/185412780-4d5ab7c9-5fb8-46b8-9ff4-c0f02c87055c.png)

橙色的是 `shapely.vectorized.contains` 方法，除非点特别多，不然其速度会更快一些。

2022-08-18 14:40 UTC, Clarmy commented
@ZhaJiMan 仓库CI使用 [black](https://github.com/psf/black) 做了风格限制，如果不符合代码规范CI不会通过，本次PR的CI显示代码风格未通过：https://github.com/cnmetlab/cnmaps/runs/7900363046?check_suite_focus=true#step:6:24 
修改方式：
1. 本地安装 black: `pip install black`
2. 在项目根目录下执行 `black .`
3. 提交代码

2022-08-18 14:49 UTC, Clarmy requested changes

2022-08-18 14:49 UTC, Clarmy commented on cnmaps/maps.py
> -
这个方法是删除了吗？我觉得是不是还是要保留啊？

2022-08-18 16:21 UTC, Clarmy requested changes

2022-08-18 16:21 UTC, Clarmy commented on cnmaps/maps.py
> +        return ~contains(self, lons, lats)
```suggestion
	lons = np.atleast_1d(lons)
        lats = np.atleast_1d(lats)
        
	if len(lons.shape) != 2 or len(lats.shape) != 2:
            raise ValueError("x或y不是2维数组")

        if lons.shape != lats.shape:
            raise ValueError("x和y的形状不匹配")
            
        return ~contains(self, lons, lats)
```

2022-08-18 16:21 UTC, Clarmy commented on cnmaps/maps.py
> +        return ~contains(self, lons, lats)
因为单元测试对这个异常有用例，所以需要实现这个异常。

2022-08-19 01:17 UTC, ZhaJiMan commented
`mask_mask_array` 方法里，`contains` 函数允许接受标量、列表和数组输入，并且会自动检查形状和抛出错误，还需要在外面加一层转换和检查吗？并且检查里要求 `lons` 和 `lats` 必须是二维数组，那我要对散点类型的一维数组做 mask 就会失败了。

2022-08-19 02:36 UTC, Clarmy commented
一维数组做mask有测试用例吗？这个修改主要是为了通过之前写的测试用例。

2022-08-19 02:37 UTC, Clarmy commented
先这样上吧，可以后面根据情况再改

2022-08-19 02:39 UTC, merged